define(function () {

	var euler = {
		info: [{
			fileName: "p1",
			functionName: "multiplesOf3And5",
			solved: true,
			dependences: null,
			title: "1. Multiples of 3 and 5",
			description: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.<br/>Find the sum of all the multiples of 3 or 5 below 1000."
		}, {
			fileName: "p2",
			functionName: "evenFibonacciNumbers",
			solved: true,
			dependences: null,
			title: "2. Even Fibonacci numbers",
			description: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...<br/>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
		}, {
			fileName: "p3",
			functionName: "largestPrimeFactor",
			solved: true,
			dependences: ["getPrimes"],
			title: "3. Largest prime factor",
			description: "The prime factors of 13195 are 5, 7, 13 and 29.<br/>What is the largest prime factor of the number 600851475143?"
		}, {
			fileName: "p4",
			functionName: "largestPalindromeProduct",
			solved: true,
			dependences: ["isPalindrome"],
			title: "4. Largest palindrome product",
			description: "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.<br/>Find the largest palindrome made from the product of two 3-digit numbers."
		}, {
			fileName: "p5",
			functionName: "smallestMultiple",
			solved: true,
			dependences: ["getPrimes", "primeFactorDecomposition", "posInArray2D"],
			title: "5. Smallest multiple",
			description: "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.<br/>What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"
		}, {
			fileName: "p6",
			functionName: "sumSquareDifference",
			solved: true,
			dependences: null,
			title: "6. Sum square difference",
			description: "<p>The sum of the squares of the first ten natural numbers is,<br/>1<sup>2</sup> + 2<sup>2</sup> + ... + 10<sup>2</sup> = 385<br/>The square of the sum of the first ten natural numbers is,<br/>(1 + 2 + ... + 10)<sup>2</sup> = 55<sup>2</sup> = 3025<br/>Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.<p/><p>Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.<p/>"
		}, {
			fileName: "p7",
			functionName: "prime10001st",
			solved: true,
			dependences: ["getFirstNPrimes"],
			title: "7. 10001st prime",
			description: "<p>By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.<p/><p>What is the 10 001st prime number?<p/>"
		}, {
			fileName: "p8",
			functionName: "largestProductInSeries",
			solved: true,
			dependences: null,
			title: "8. Largest product in a series",
			description: "<p>Find the greatest product of five consecutive digits in the 1000-digit number.</p><p>73167176531330624919225119674426574742355349194934<br/>96983520312774506326239578318016984801869478851843<br/>85861560789112949495459501737958331952853208805511<br/>12540698747158523863050715693290963295227443043557<br/>66896648950445244523161731856403098711121722383113<br/>62229893423380308135336276614282806444486645238749<br/>30358907296290491560440772390713810515859307960866<br/>70172427121883998797908792274921901699720888093776<br/>65727333001053367881220235421809751254540594752243<br/>52584907711670556013604839586446706324415722155397<br/>53697817977846174064955149290862569321978468622482<br/>83972241375657056057490261407972968652414535100474<br/>82166370484403199890008895243450658541227588666881<br/>16427171479924442928230863465674813919123162824586<br/>17866458359124566529476545682848912883142607690042<br/>24219022671055626321111109370544217506941658960408<br/>07198403850962455444362981230987879927244284909188<br/>84580156166097919133875499200524063689912560717606<br/>05886116467109405077541002256983155200055935729725<br/>71636269561882670428252483600823257530420752963450</p>"
		}, {
			fileName: "p9",
			functionName: "pythagoreanTriplet",
			solved: false,
			dependences: null,
			title: "9. Special Pythagorean triplet",
			description: "<p>A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,<p/><p>a2 + b2 = c2<br/>For example, 32 + 42 = 9 + 16 = 25 = 52.</p><p>There exists exactly one Pythagorean triplet for which a + b + c = 1000.<br/>Find the product abc.<p/>"
		}]
	}

	return euler;
});